[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "size"
show_hidden = true
show_symlink = true

[preview]
cache_dir = "~/.cache/yazi"
image = "ueberzugpp"

[opener]
edit_nvim = [
    { run = '${EDITOR:=nvim} "$@"', desc = "Edit (nvim)", block = true },
]

play_vlc = [{ run = 'vlc "$@"', desc = "Play (VLC)", orphan = true }]
play_mpv = [{ run = 'mpv --force-window "$@"', desc = "Play (mpv)", orphan = true }]

view_ristretto = [
    { run = 'ristretto "$@"', desc = "View (Ristretto)", block = true },
]

reveal = [
    { run = 'alacritty --working-directory="$(dirname "$1")" &', desc = "Dir", orphan = true },
]

archive_zip = [
    { run = 'zip -r "${1%.zip}.zip" "$@"', desc = "Archive (zip)", block = true },
]
extract_zip = [
    { run = 'unzip "$1" -d "${1%.*}"', desc = "Extract (unzip)", block = true },
]

archive_7z = [
    { run = '7z a "${1%.7z}.7z" "$@"', desc = "Archive (7z)", block = true },
]
extract_7z = [
    { run = '7z x "$1" -o"${1%.*}"', desc = "Extract (7z)", block = true },
]

[open]
rules = [
    { name = "*/", use = [
        "edit_nvim",
        "reveal",
        "archive_zip",
        "archive_7z",
    ] },
    { mime = "text/*", use = [
        "edit_nvim",
        "reveal",
        "archive_zip",
        "archive_7z",
    ] },
    { mime = "inode/x-empty", use = [
        "edit_nvim",
        "reveal",
        "archive_zip",
        "archive_7z",
    ] },
    { mime = "application/json", use = [
        "edit_nvim",
        "reveal",
        "archive_zip",
        "archive_7z",
    ] },
    { mime = "image/*", use = [
        "view_ristretto",
        "reveal",
        "archive_zip",
        "archive_7z",
    ] },
    { mime = "{audio,video}/*", use = [
        "play_vlc",
        "play_mpv",
        "reveal",
        "archive_zip",
        "archive_7z",
    ] },
    { mime = "application/pdf", use = [
        "reveal",
        "archive_zip",
        "archive_7z",
    ] },
    { mime = "application/zip", use = [
        "extract_zip",
        "reveal",
    ] },
    { mime = "application/x-7z-compressed", use = [
        "extract_7z",
        "reveal",
    ] },
    { name = "*", use = [
        "edit_nvim",
        "reveal",
        "archive_zip",
        "archive_7z",
        "extract_zip",
    ] },
]
